language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - CAKE_VERSION=2.2.9
  - CAKE_VERSION=2.3.10
  - CAKE_VERSION=master
  - CAKE_VERSION=2.5

matrix:
  exclude:
    - php: 5.4
      env: CAKE_VERSION=2.2.9
    - php: 5.5
      env: CAKE_VERSION=2.2.9

before_script:
  - composer global require 'phpunit/phpunit=3.7.33'
  - git clone --depth 1 git://github.com/cakephp/cakephp --branch $CAKE_VERSION ../cakephp && cd ../cakephp
  - ln -s ~/.composer/vendor/phpunit/phpunit/PHPUnit vendors/PHPUnit
  - git clone --depth 1 git://github.com/facebook/xhprof.git vendors/xhprof
  - sh -c "cd vendors/xhprof/extension && phpize && ./configure --enable-xhprof && make && sudo make install"
  - echo -ne "[xdebug]\nextension=xhprof.so\nxhprof.output_dir=/tmp" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - echo 'Configure::write("XHProf.library", dirname(APP) . "/vendors/xhprof/xhprof_lib");' >> app/Config/bootstrap.php
  - cp -R ../CakePHP-XHProf plugins/XHProf
  - echo "<phpunit>
      <filter>
        <whitelist processUncoveredFilesFromWhitelist=\"true\">
          <directory suffix=\".php\">$(pwd)/plugins/XHProf</directory>
          <exclude>
            <file>$(pwd)/plugins/XHProf/Lib/Panel/XHProfPanel.php</file>
            <directory suffix=\".php\">$(pwd)/plugins/XHProf/Test</directory>
          </exclude>
        </whitelist>
      </filter>
      <logging>
        <log type=\"coverage-text\" target=\"php://stdout\" showUncoveredFiles=\"false\" />
      </logging>
    </phpunit>" > phpunit.xml

script:
  - ./lib/Cake/Console/cake test XHProf AllXHProf

notifications:
  email: false
